config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" } do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  namespace :api, defaults: { format: 'json' } do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      get 'artists', to: 'artists#index', as: 'index'
      get '/search', to: 'artists#search', as: 'search'
      # TODO: if i had more time, add the rest of the CRUD operations for the artists resource
    end
  end


end

app/models/artist.rb
class Artist < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules.
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable,
          :confirmable, :omniauthable, omniauth_providers: [:google_oauth2]

  def self.from_omniauth(details)
    u = User.find_or_initialize_by(
      email: details['info']['email']
    )
    u.first_name = details['info']['first_name']
    u.last_name = details['info']['last_name']

    u.password = SecureRandom.urlsafe_base64
    u.skip_confirmation!
    u.save
    return u
  end
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ApplicationController
  respond_to :json
  # TODO: authentication stuff would go here
end

app/controllers/api/v1/artists_controller.rb
module Api
  module V1
    class ArtistsController < ApiController

      def index
        render json: Artist.all, status: :ok
      end

      def search
        term = params[:term] || nil
        if term
          artists = Artist.where(
            "name LIKE :term OR handle LIKE :term OR tags LIKE :term OR location LIKE :term", term: "%#{term}%"
          )
        else
          artists = Artist.all
        end

        render json: artists, status: :ok

      end
      
      # TODO: if i had more time, add the rest of the CRUD operations for the artists resource


      private

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:handle, :url, :name, :bio, :members, :website, :wiki_page, :donation_url, :tags, :location)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :handle %><br>
    <%= f.text_field :handle %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :members %><br>
    <%= f.text_field :members %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :wiki_page %><br>
    <%= f.text_field :wiki_page %>
  </div>
  <div class="field">
    <%= f.label :donation_url %><br>
    <%= f.text_field :donation_url %>
  </div>
  <div class="field">
    <%= f.label :tags %><br>
    <%= f.text_field :tags %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Artists</h1>

<table>
  <thead>
    <tr>
      <th>Handle</th>
      <th>Url</th>
      <th>Name</th>
      <th>Bio</th>
      <th>Members</th>
      <th>Website</th>
      <th>Wiki page</th>
      <th>Donation url</th>
      <th>Tags</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @artists.each do |artist| %>
      <tr>
        <td><%= artist.handle %></td>
        <td><%= artist.url %></td>
        <td><%= artist.name %></td>
        <td><%= artist.bio %></td>
        <td><%= artist.members %></td>
        <td><%= artist.website %></td>
        <td><%= artist.wiki_page %></td>
        <td><%= artist.donation_url %></td>
        <td><%= artist.tags %></td>
        <td><%= artist.location %></td>
        <td><%= link_to 'Show', artist %></td>
        <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
        <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artist', new_artist_path %>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Handle:</strong>
  <%= @artist.handle %>
</p>

<p>
  <strong>Url:</strong>
  <%= @artist.url %>
</p>

<p>
  <strong>Name:</strong>
  <%= @artist.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @artist.bio %>
</p>

<p>
  <strong>Members:</strong>
  <%= @artist.members %>
</p>

<p>
  <strong>Website:</strong>
  <%= @artist.website %>
</p>

<p>
  <strong>Wiki page:</strong>
  <%= @artist.wiki_page %>
</p>

<p>
  <strong>Donation url:</strong>
  <%= @artist.donation_url %>
</p>

<p>
  <strong>Tags:</strong>
  <%= @artist.tags %>
</p>

<p>
  <strong>Location:</strong>
  <%= @artist.location %>
</p>

<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>

app/views/home/index.html.erb
<div class="container">
  <div class="form-group">
    <input type="text" class='form-control' id='search' placeholder="type to filter">
  </div>
  <div class="results">
    <div class="prompt">
      <div class="heading">Enter 3+ characters to search artists.</div>
    </div>
    <div class="loading" hidden>
      <div class="loader"></div>
    </div>
    <div class="complete">
    </div>
  </div>


</div>

<script type="text/javascript">

$( "#search" ).keyup(function() {
  // hand-rolled custom search feature
  filterValue = $('#search').val()
  if(filterValue.length>2) {
    searchArtists(filterValue);
  } else {
    resetPrompt();
  }
});

function searchArtists(filterValue) {
  $.ajax({
    type: 'GET',
    dataType: 'json',
    url: `<%= escape_javascript api_search_url %>?term=${filterValue}`,
    success: function(data) {
      populateResults(data);
    }
  });

}

function populateResults(data){
  $('.heading').text(`Results (${data.length})`);
  html = "";
  $.each(data, function (key,val) {
    var key = key;
    var url = val.website || val.donation_url || val.url
    var imageUrl = val.image_url || "https://www.iconexperience.com/_img/g_collection_png/standard/512x512/singer.png"
    if(!checkURL(imageUrl)){
      imageUrl = "https://www.iconexperience.com/_img/g_collection_png/standard/512x512/singer.png"
    }
    html += `<div class="row">`;
    html +=   `<div class="avatar col-sm-6">`;
    html +=     `<img src="`+imageUrl+`" alt="">`;
    html +=   `</div>`;
    html +=   `<div class="information col-sm-6">`
    html +=     `<div class="info-item"><u>Name/Handle</u>: `+ val.name || val.handle +`</div>`
    html +=     `<div class="info-item"><u>Url</u>: <a href="`+url+`">`+truncateString(url,25)+`</a></div>`
    html +=     `<div class="info-item"><u>Members</u>: `+val.members+`</div>`
    html +=     `<div class="info-item"><u>Tags</u>: `+val.tags+`</div>`
    html +=   `</div>`
    html += `</div>`
    html += `</div>`
    if(key != data.length-1){
      html += `<div class="divider"></div>`
    }
  });
  $('.complete').html(html);
}

function resetPrompt(){
  $('.heading').text('Enter 3+ characters to search artists.');
  $('.complete').html('');
}

function truncateString(str, num) {
  if (num > str.length){
    return str
  } else {
    return str.slice(0,num) + "...";
  }

}

function checkURL(url) {
    return(url.match(/\.(jpeg|jpg|gif|png)$/) != null);
}




</script>

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<%= ENV['GOOGLE_ANALYTICS_ID'] %>', 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/_nav.html.erb
<nav class="navbar fixed-top navbar-light bg-light">
  <a class="navbar-brand" href="/">ArtistSearch</a>
  <ul class="nav navbar-nav navbar-right">
    <% if current_user %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Hello <%= current_user.try(:first_name) %> <span class="caret"></span></a>
      <ul class="dropdown-menu">
        <li>
          <%= link_to 'Log out', destroy_user_session_path, class: 'nav-link', :method => 'delete' %>
        </li>
      </ul>
    </li>
    <% else %>
      <li><%= link_to 'Log In/ Sign Up', new_user_session_path, class: 'nav-link' %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/_notification.html.erb
<div class="notification">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>  alert-dismissable">
      <button type="button" class="close close-notification" data-dismiss="alert" aria-hidden="true">&times;</button>
      <strong><%= msg %></strong>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Artist Api</title>
  <%= javascript_include_tag 'application' %>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>

  <!-- Latest compiled and minified JavaScript -->
  <%= csrf_meta_tags %>
  <!-- this is always required for mobile responsiveness! -->
  <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <%= render 'layouts/nav' %>
  <%= render 'layouts/notification' %>
  <%= yield %>
  <%= render 'layouts/google_analytics' %>

</body>
</html>